version: "3"

volumes:
  db-data:

services:
  test-db:
    image: mysql:latest
    ports:
      - 8891:8080
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: johndoe
      MYSQL_PASSWORD: randompassword
      MYSQL_DATABASE: awas_test
    restart: always
